Repository hmcts/juror-api, pull requests merged in 2024-02, with the labels that each got.

#19 add dashboard schema
  config/owasp/suppressions.xml
  infrastructure/sdp.tf
Labels: destroy

#24 add Appinsights dependency
  build.gradle
Labels: ns:juror, prd:juror, rel:juror-api-pr-24

#23 enable intergration tests
  build.gradle
  src/functionalTest/java/uk/gov/hmcts/juror/api/bureau/notify/JurorCommsNotifyAdapterImplTest.java
  src/functionalTest/java/uk/gov/hmcts/juror/api/bureau/notify/NotifyAdapterImplTest.java
  src/functionalTest/resources/db/notify_adapter_pool.sql
  src/functionalTest/resources/db/notify_template_mapping.sql
  src/functionalTest/resources/db/welsh_enabled.sql
  src/integration-test/java/uk/gov/hmcts/juror/api/AbstractIntegrationTest.java
  src/integration-test/java/uk/gov/hmcts/juror/api/ValidationTest.java
  src/integration-test/java/uk/gov/hmcts/juror/api/bureau/notify/JurorCommsNotifyTemplateTypeIntegrationTest.java
  src/integration-test/java/uk/gov/hmcts/juror/api/bureau/service/JurorCommsNotificationServiceImplIntegrationTest.java
  src/integration-test/java/uk/gov/hmcts/juror/api/config/SecurityConfigTest.java
  src/integration-test/java/uk/gov/hmcts/juror/api/juror/controller/PublicFrontendLogControllerTest.java
  src/integration-test/java/uk/gov/hmcts/juror/api/juror/notify/NotifyTemplateTypeIntegrationTest.java
  src/integration-test/java/uk/gov/hmcts/juror/api/moj/domain/HolidayITest.java
  src/integration-test/java/uk/gov/hmcts/juror/api/moj/domain/PoolCreateITest.java
  src/integration-test/java/uk/gov/hmcts/juror/api/moj/domain/PoolRequestITest.java
  src/integration-test/java/uk/gov/hmcts/juror/api/moj/domain/jurorresponse/JurorResponseITest.java
  src/integration-test/java/uk/gov/hmcts/juror/api/moj/service/PoolRequestSearchServiceITest.java
  src/integration-test/java/uk/gov/hmcts/juror/api/testsupport/ContainerTest.java
  src/integration-test/java/uk/gov/hmcts/juror/api/testsupport/PostgresqlContainer.java
  src/integration-test/resources/db/JurorExpenseControllerITest_approveExpenseSetUp.sql
  src/integration-test/resources/db/JurorExpenseControllerITest_calculateTotalExpenseSetUp.sql
  src/integration-test/resources/db/JurorExpenseControllerITest_draftExpenseSetUp.sql
  src/integration-test/resources/db/JurorExpenseControllerITest_editExpenseSetUp.sql
  src/integration-test/resources/db/JurorExpenseControllerITest_getApproveExpenseSetUp.sql
  src/integration-test/resources/db/JurorExpenseControllerITest_simplifiedExpenseSetUp.sql
  src/main/java/uk/gov/hmcts/juror/api/moj/domain/RevisionInfo.java
  src/main/resources/db/migration/V1_17__added_public_schema.sql
Labels: ns:juror, prd:juror, rel:juror-api-pr-23

#40 jcde-26feb-merge
  build.gradle
  src/integration-test/java/uk/gov/hmcts/juror/api/moj/controller/JurorExpenseControllerITest.java
  src/integration-test/java/uk/gov/hmcts/juror/api/moj/controller/JurorManagementControllerITest.java
  src/integration-test/java/uk/gov/hmcts/juror/api/moj/controller/JurorRecordControllerITest.java
  src/integration-test/java/uk/gov/hmcts/juror/api/moj/controller/LetterControllerITest.java
  src/integration-test/resources/db/JurorExpenseControllerITest_approveExpenseSetUp.sql
  src/integration-test/resources/db/JurorExpenseControllerITest_calculateTotalExpenseSetUp.sql
  src/integration-test/resources/db/JurorExpenseControllerITest_draftExpenseSetUp.sql
  src/integration-test/resources/db/JurorExpenseControllerITest_editExpenseSetUp.sql
  src/integration-test/resources/db/JurorExpenseControllerITest_getApproveExpenseSetUp.sql
  src/integration-test/resources/db/JurorExpenseControllerITest_getEnteredExpenseDetails.sql
  src/integration-test/resources/db/JurorExpenseControllerITest_setUp_default_expenses.sql
  src/integration-test/resources/db/JurorExpenseControllerITest_simplifiedExpenseSetUp.sql
  src/integration-test/resources/db/JurorRecordController_initAttendanceTests.sql
  src/integration-test/resources/db/jurormanagement/InitAppearanceTests.sql
  src/integration-test/resources/db/letter/LetterController_initSummonsReminderLetter.sql
  src/main/java/uk/gov/hmcts/juror/api/juror/domain/PoolCourt.java
  src/main/java/uk/gov/hmcts/juror/api/juror/service/ExcusedCompletedCourtCommsServiceImpl.java
  src/main/java/uk/gov/hmcts/juror/api/juror/service/MessagesServiceImpl.java
  src/main/java/uk/gov/hmcts/juror/api/moj/controller/JurorExpenseController.java
  src/main/java/uk/gov/hmcts/juror/api/moj/controller/request/JurorNumberAndPoolNumberDto.java
  src/main/java/uk/gov/hmcts/juror/api/moj/controller/request/ReissueLetterListRequestDto.java
  src/main/java/uk/gov/hmcts/juror/api/moj/controller/request/expense/ApportionSmartCardRequest.java
  src/main/java/uk/gov/hmcts/juror/api/moj/controller/request/expense/ApproveExpenseDto.java
  src/main/java/uk/gov/hmcts/juror/api/moj/controller/request/expense/ExpenseItemsDto.java
  src/main/java/uk/gov/hmcts/juror/api/moj/controller/request/letter/court/CourtLetterListRequestDto.java
  src/main/java/uk/gov/hmcts/juror/api/moj/controller/response/JurorAttendanceDetailsResponseDto.java
  src/main/java/uk/gov/hmcts/juror/api/moj/controller/response/ReissueLetterListResponseDto.java
  src/main/java/uk/gov/hmcts/juror/api/moj/domain/Appearance.java
  src/main/java/uk/gov/hmcts/juror/api/moj/domain/FormCode.java
  src/main/java/uk/gov/hmcts/juror/api/moj/enumeration/AttendanceType.java
  src/main/java/uk/gov/hmcts/juror/api/moj/enumeration/PayAttendanceType.java
  src/main/java/uk/gov/hmcts/juror/api/moj/enumeration/letter/LetterType.java
  src/main/java/uk/gov/hmcts/juror/api/moj/repository/IAppearanceRepository.java
  src/main/java/uk/gov/hmcts/juror/api/moj/repository/IAppearanceRepositoryImpl.java
  src/main/java/uk/gov/hmcts/juror/api/moj/repository/IReissueLetterRepositoryImpl.java
  src/main/java/uk/gov/hmcts/juror/api/moj/service/JurorRecordServiceImpl.java
  src/main/java/uk/gov/hmcts/juror/api/moj/service/PrintDataService.java
  src/main/java/uk/gov/hmcts/juror/api/moj/service/PrintDataServiceImpl.java
  src/main/java/uk/gov/hmcts/juror/api/moj/service/ReissueLetterServiceImpl.java
  src/main/java/uk/gov/hmcts/juror/api/moj/service/expense/JurorExpenseService.java
  src/main/java/uk/gov/hmcts/juror/api/moj/service/expense/JurorExpenseServiceImpl.java
  src/main/java/uk/gov/hmcts/juror/api/moj/service/jurormanagement/JurorAppearanceServiceImpl.java
  src/main/java/uk/gov/hmcts/juror/api/moj/xerox/LetterBase.java
  src/main/java/uk/gov/hmcts/juror/api/moj/xerox/letters/SummonsReminderLetter.java
  src/main/java/uk/gov/hmcts/juror/api/validation/ValidateIfValidator.java
  src/main/resources/db/migration/V1_10__Create_Missing_Migration_Tables.sql
  src/main/resources/db/migration/V1_14__appearance_tidy_up.sql
  src/main/resources/db/migration/V1_15__Update_Get_Active_Pools_At_Court_Function.sql
  src/test/java/uk/gov/hmcts/juror/api/juror/service/JurorServiceImplTest.java
  src/test/java/uk/gov/hmcts/juror/api/moj/controller/JurorExpenseControllerTest.java
  src/test/java/uk/gov/hmcts/juror/api/moj/domain/AppearanceTest.java
  src/test/java/uk/gov/hmcts/juror/api/moj/enumeration/AttendanceTypeTest.java
  src/test/java/uk/gov/hmcts/juror/api/moj/enumeration/LetterTypeTest.java
  src/test/java/uk/gov/hmcts/juror/api/moj/enumeration/PayAttendanceTypeTest.java
  src/test/java/uk/gov/hmcts/juror/api/moj/repository/IReissueLetterRepositoryImplTest.java
  src/test/java/uk/gov/hmcts/juror/api/moj/service/JurorRecordServiceTest.java
  src/test/java/uk/gov/hmcts/juror/api/moj/service/expense/JurorExpenseServiceTest.java
  src/test/java/uk/gov/hmcts/juror/api/moj/service/jurormanagement/JurorAppearanceServiceTest.java
  src/test/java/uk/gov/hmcts/juror/api/moj/xerox/SummonsReminderLetterTest.java
Labels: ns:juror, prd:juror, rel:juror-api-pr-40

#57 remove ITHC from sdp user list
  infrastructure/sdp.tf
Labels: no-changes, ns:juror, prd:juror, rel:juror-api-pr-57
